# Generated by Django 4.2.6 on 2023-11-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
